# Generated by Django 6.0 on 2026-02-01 22:02

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок (необязательно)')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 1920x600', upload_to='banners/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Apple, Samsung, Xiaomi', max_length=255, unique=True, verbose_name='Название бренда')),
                ('slug', models.SlugField(help_text='Используется в ссылке. Например: apple, samsung', max_length=200, unique=True, verbose_name='URL-адрес (slug)')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('work_time', models.CharField(help_text='Пример: 9:00–22:00 ежедневно', max_length=100, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Отображается в каталоге и на главной странице', upload_to='categories/', verbose_name='Изображение категории')),
                ('name', models.CharField(help_text='Например: Телефоны, Ноутбуки', max_length=255, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Используется в ссылке. Например: phones, laptops', max_length=200, unique=True, verbose_name='URL-адрес (slug)')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('stock_status', models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии'), ('preorder', 'Под заказ')], default='in_stock', max_length=50, verbose_name='Статус наличия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Наличие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sku', models.CharField(default=store.models.generate_sku, editable=False, max_length=12, unique=True, verbose_name='Артикул')),
                ('brands', models.ManyToManyField(blank=True, to='store.brand', verbose_name='Бренды')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=255, verbose_name='Значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Атрибут товара',
                'verbose_name_plural': 'Атрибуты товаров',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(help_text='Выберите категории, к которым относится бренд', related_name='brands', to='store.productcategory', verbose_name='Категории'),
        ),
        migrations.CreateModel(
            name='ProductColorAngle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
                ('image_1', models.ImageField(upload_to='products/gallery/', verbose_name='Изображение товара')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Ракурс 1')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Ракурс 2')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Ракурс 3')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Ракурс 4')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Ракурс 5')),
                ('is_available', models.BooleanField(default=True, help_text='Если цвет есть на складе, оставьте включённым', verbose_name='В наличии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара и цвет',
                'verbose_name_plural': 'Изображение товара и цвета',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductMemoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Объем памяти')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена для этого объема памяти')),
                ('colors', models.ManyToManyField(related_name='memory_options', to='store.productcolorangle', verbose_name='Доступные цвета')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_options_all', to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Вариант памяти',
                'verbose_name_plural': 'Варианты памяти',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productcolorangle')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productmemoryoption')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, help_text='Никнейм', max_length=100, null=True, verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, help_text='Kод страны без(+) 996 ...', max_length=100, null=True, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, help_text='Никнейм', max_length=100, null=True, verbose_name='Telegram')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='store.contacts', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Избранный товар',
                'verbose_name_plural': 'Избранные товары',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.AddConstraint(
            model_name='productcolorangle',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_color_name'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product', 'color', 'memory')},
        ),
    ]
